/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auth;

import Customer.MainMenuCust;
import javax.swing.JOptionPane;
import connection.DBConnection;
import dao.DAO_Login;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Admin.*;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public Login() {
        initComponents();

        // Since we are not maintaining any user profile so - 
        // let's set the default user and password
        setDefaultUserName();
    }

    /**
     * Set default username and password
     */
    private void setDefaultUserName() {
        this.userNameField.setText("");
        this.passwordField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        show = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(153, 153, 255));
        loginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GamingStore", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        loginPanel.setForeground(new java.awt.Color(153, 153, 255));
        loginPanel.setToolTipText("");
        loginPanel.setName(""); // NOI18N
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/visible.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        loginPanel.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hide.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        loginPanel.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        userNameLabel.setBackground(new java.awt.Color(255, 153, 153));
        userNameLabel.setForeground(new java.awt.Color(0, 0, 255));
        userNameLabel.setText("User Name: ");
        loginPanel.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 44, 89, -1));

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        loginPanel.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 41, 120, -1));

        passwordLabel.setForeground(new java.awt.Color(0, 0, 204));
        passwordLabel.setText("Password :");
        loginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 84, -1, -1));

        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 117, -1, -1));
        loginPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 81, 120, -1));

        jLabel1.setText("Belum punya akun?");
        loginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 152, -1, -1));

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Registrasi");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 152, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Pristina", 1, 35)); // NOI18N
        jLabel4.setText("STORE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 40));

        jLabel3.setFont(new java.awt.Font("Pristina", 1, 35)); // NOI18N
        jLabel3.setText("EIGHT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gaming-logo-49554.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, 170));

        loginPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 360, 330));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 360));
        loginPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    // Get entered username and password from your UI components
    String enteredUsername = userNameField.getText(); // Replace with your actual text field component
    String enteredPassword = new String(passwordField.getPassword()); // Replace with your actual password field component

    DAO_Login daoLogin = new DAO_Login();

    if (daoLogin.verifyUserCredentials(enteredUsername, enteredPassword)) {
        if ("Admin".equals(enteredUsername)) {
            JOptionPane.showMessageDialog(this, "Admin login successful");            
            Dashboard bro = new Dashboard();
            bro.setVisible(true);
            this.dispose();
            

        } else {
            JOptionPane.showMessageDialog(this, "Login successful");
            MainMenuCust ai = new MainMenuCust();
            ai.setVisible(true);
            this.dispose();

        }
    } else {
        JOptionPane.showMessageDialog(this, "Login failed");
    }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Register rg = new Register();
        rg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        show.setVisible(false);
        hide.setVisible(true);
        passwordField.setEchoChar((char)0);// TODO add your handling code here:
    }//GEN-LAST:event_showMouseClicked

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        show.setVisible(true);
        hide.setVisible(false);
        passwordField.setEchoChar('*');        // TODO add your handling code here:
    }//GEN-LAST:event_hideMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel show;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables

}
